# Generated by Django 5.1.6 on 2025-08-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventplannerprofile_ngoprofile_restaurantprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddonation',
            options={'ordering': ['-posted_at']},
        ),
    ]
