# Generated by Django 4.2.24 on 2025-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fooddonation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='people_served',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people served when donation is completed', null=True),
        ),
    ]
