# Generated by Django 4.2.24 on 2025-09-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collaboration_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='total_people_served',
            field=models.PositiveIntegerField(default=0, help_text='Total number of people served across all completed donations'),
        ),
    ]
