# Generated by Django 5.1.6 on 2025-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analysis_total_people_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='monthly_people_served',
            field=models.PositiveIntegerField(default=0, help_text='Number of people served in current month'),
        ),
    ]
