# Generated by Django 5.1.6 on 2025-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_analysis_monthly_people_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='badge_level',
            field=models.CharField(blank=True, help_text='Current badge level based on monthly performance', max_length=20, null=True),
        ),
    ]
