# Generated by Django 5.1.6 on 2025-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_analysis_badge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='monthly_donations_made',
            field=models.PositiveIntegerField(default=0, help_text='Number of donations made in current month'),
        ),
    ]
