# Generated by Django 5.1.6 on 2025-07-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RESTAURANT', 'Restaurant'), ('NGO', 'Ngo'), ('EVENTPLANNER', 'Event Planner')], default='RESTAURANT', max_length=50),
        ),
    ]
