# Generated by Django 5.1.6 on 2025-07-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
