"""
Django settings for grace_bites_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# --- VERCEL DEPLOYMENT SETTINGS ---

# 1. SECRET_KEY
# If the environment variable SECRET_KEY exists, use it. Otherwise, use a fallback
# for local development (or raise an error if needed).
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-3f#+ho%nx4f0dl19#6w+gg3+#(w27oo(czdt&szd$%n!6j3g7m' # Use a temporary dummy key for local fallback if necessary
) 

# 2. DEBUG
# Set DEBUG based on the environment variable, defaulting to True for safety locally.
# Vercel will set this to 'False' based on your configuration.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# 3. ALLOWED_HOSTS
# Read ALLOWED_HOSTS from the environment variable and split it by comma.
# Fallback to an empty list or specific localhost for local development.
# We also ensure the production URL is always an allowed host when DEBUG is False.
if not DEBUG:
    allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '')
    if allowed_hosts_str:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]
    else:
        # If no ALLOWED_HOSTS set in production, allow all Vercel domains
        # This prevents DisallowedHost errors during initial deployment
        # TODO: Set ALLOWED_HOSTS environment variable in Vercel for security!
        ALLOWED_HOSTS = ['*', '.vercel.app']
        import warnings
        warnings.warn("ALLOWED_HOSTS not set in production! Set it in Vercel environment variables.")
else:
    # Use standard localhost only during local development
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# --- END VERCEL DEPLOYMENT SETTINGS ---

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'grace_bites_project.middleware.CSRFDebugMiddleware',
    'grace_bites_project',
    
    # WhiteNoise for serving static files on Vercel
    # Note: WhiteNoise middleware handles static file serving

    # My apps
    'accounts',
    'core',
    'restaurant',
    'ngo',
    'eventplanner',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise middleware - must be right after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Temporarily disabled
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'grace_bites_project.middleware.CSRFDebugMiddleware',
]

ROOT_URLCONF = 'grace_bites_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grace_bites_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Try to use dj-database-url if DATABASE_URL is set (common on Vercel/Heroku)
# Otherwise, use individual environment variables or fallback to SQLite
try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Check for DATABASE_URL first (Vercel Postgres, Heroku, etc.)
database_url = os.environ.get('DATABASE_URL')
if database_url and dj_database_url:
    # Use dj-database-url to parse DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('DB_NAME'):
    # Use PostgreSQL if individual database credentials are provided
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # Fallback to SQLite for local development
    # NOTE: SQLite will NOT work on Vercel - you need PostgreSQL!
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT is where collectstatic will gather all static files
# This is required for WhiteNoise to serve static files on Vercel
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_DIRS tells Django where to find static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# WhiteNoise configuration for serving static files
# WhiteNoise will serve files from STATIC_ROOT in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
# NOTE: On Vercel, you should use cloud storage (S3, Cloudinary, etc.)
# Local media storage won't persist on serverless functions
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# CSRF Settings
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')
# Add Vercel domain to trusted origins if set
vercel_url = os.environ.get('VERCEL_URL')
if vercel_url:
    CSRF_TRUSTED_ORIGINS.append(f'https://{vercel_url}')
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = False
